// website/.vitepress/components/HylimoEditor.vue
<template>
    <div :class="{ hidden: hideMainContent }">
        <Splitpanes :horizontal="horizontal">
            <Pane>
                <div ref="editorElement" class="editor-element"></div>
            </Pane>
            <Pane>
                <div ref="sprottyWrapper" class="sprotty-wrapper">
                    <div :id="`sprotty-container-${id}`"></div>
                </div>
            </Pane>
        </Splitpanes>
    </div>
</template>
<script setup lang="ts">
import "reflect-metadata";
// @ts-ignore
import { Splitpanes, Pane } from "splitpanes";
import "splitpanes/dist/splitpanes.css";
import { ref, onBeforeUnmount } from "vue";
import { ActionHandlerRegistry, IActionDispatcher, TYPES } from "sprotty";
import { RequestModelAction, ActionMessage } from "sprotty-protocol";
import {
    DiagramActionNotification,
    DiagramOpenNotification,
    PublishDocumentRevealNotification,
    TransactionalAction
} from "@hylimo/diagram-protocol";
import { createContainer, DiagramServerProxy, ResetCanvasBoundsAction } from "@hylimo/diagram-ui";
import { Root } from "@hylimo/diagram-common";
import { onMounted } from "vue";
import { MonacoEditorLanguageClientWrapper, UserConfig } from "monaco-editor-wrapper";
import { shallowRef } from "vue";
import { inject } from "vue";
import { language, languageClientKey } from "../theme/lspPlugin";
import { Disposable } from "vscode-languageserver-protocol";
import { useResizeObserver } from "@vueuse/core";
import { v4 as uuid } from "uuid";

const id = uuid();

defineProps({
    horizontal: {
        type: Boolean,
        default: false
    }
});

const emit = defineEmits<{
    "update:diagram": [diagram: Root];
}>();

const model = defineModel({
    type: String,
    required: true
});

/**
 * Enum which controls the current transaction state
 * Used for handling undo stops, which should be ignored during transactions
 */
enum TransactionState {
    /**
     * No transaction is in progress
     */
    None,
    /**
     * Transaction is in progress, ignore undo stops
     */
    InProgress,
    /**
     * Transaction is committed, go to normal mode after next final edit
     */
    Committed
}

const editorElement = ref<HTMLElement | null>(null);
const sprottyWrapper = ref<HTMLElement | null>(null);
const disposables = shallowRef<Disposable[]>([]);
const languageClient = inject(languageClientKey)!;
const actionDispatcher = shallowRef<IActionDispatcher>();
const transactionState = ref(TransactionState.None);
const hideMainContent = ref(true);

useResizeObserver(sprottyWrapper, () => {
    actionDispatcher.value?.dispatch({ kind: ResetCanvasBoundsAction.KIND } satisfies ResetCanvasBoundsAction);
});

onMounted(async () => {
    const currentLanguageClient = await languageClient.value;
    const wrapper = new MonacoEditorLanguageClientWrapper();
    disposables.value.push(wrapper);
    const userConfig: UserConfig = {
        wrapperConfig: {
            editorAppConfig: {
                $type: "classic",
                editorOptions: {
                    language,
                    value: model.value,
                    automaticLayout: true,
                    fixedOverflowWidgets: true,
                    hover: {
                        above: false
                    },
                    suggest: {
                        snippetsPreventQuickSuggestions: false
                    },
                    scrollbar: {
                        alwaysConsumeMouseWheel: false
                    }
                }
            }
        }
    };

    await wrapper.initAndStart(userConfig, editorElement.value!);

    const editor = wrapper.getEditor()!;
    hideMainContent.value = false;

    const editorModel = editor.getModel()!;
    const pushStackElement = editorModel.pushStackElement;

    // override pushStackElement to ignore undo stops during transactions
    editorModel.pushStackElement = () => {
        if (transactionState.value == TransactionState.None) {
            pushStackElement.call(editorModel);
        }
    };

    editorModel.onDidChangeContent(() => {
        model.value = editor.getValue();
        if (transactionState.value == TransactionState.Committed) {
            // it's important to do this here, as by this, the undo stop before applying the last update is still ignored,
            // while the undo stop after applying counts as a normal undo stop
            transactionState.value = TransactionState.None;
        }
    });

    const uri = editor.getModel()?.uri?.toString();

    const revealHandler = currentLanguageClient.onNotification(PublishDocumentRevealNotification.type, (message) => {
        if (editor && message.uri == uri) {
            const range = message.range;
            const editorRange = {
                startLineNumber: range.start.line + 1,
                startColumn: range.start.character + 1,
                endLineNumber: range.end.line + 1,
                endColumn: range.end.character + 1
            };
            editor.setSelection(editorRange);
            editor.revealRange(editorRange);
        }
    });
    disposables.value.push(revealHandler);

    if (uri == undefined) {
        throw new Error("Missing editor or model");
    }
    currentLanguageClient.sendNotification(DiagramOpenNotification.type, {
        clientId: uri,
        diagramUri: uri
    });

    class LspDiagramServerProxy extends DiagramServerProxy {
        override clientId = uri!;

        override initialize(registry: ActionHandlerRegistry): void {
            super.initialize(registry);
            const handler = currentLanguageClient.onNotification(DiagramActionNotification.type, (message) => {
                if (
                    "newRoot" in message.action &&
                    message.action.newRoot != undefined &&
                    message.clientId == this.clientId
                ) {
                    emit("update:diagram", message.action.newRoot as Root);
                }
                this.messageReceived(message);
            });
            disposables.value.push(handler);
        }

        protected override sendMessage(message: ActionMessage): void {
            currentLanguageClient.sendNotification(DiagramActionNotification.type, message);
        }

        protected override handleUndo(): void {
            editor.trigger("diagram", "undo", {});
        }

        protected override handleRedo(): void {
            editor.trigger("diagram", "redo", {});
        }

        protected override handleTransactionStart(): void {
            editorModel.pushStackElement();
            transactionState.value = TransactionState.InProgress;
        }

        protected override handleTransactionCommit(): void {
            transactionState.value = TransactionState.Committed;
        }
    }

    const container = createContainer(`sprotty-container-${id}`);
    container.bind(LspDiagramServerProxy).toSelf().inSingletonScope();
    container.bind(TYPES.ModelSource).toService(LspDiagramServerProxy);
    const currentActionDispatcher = container.get<IActionDispatcher>(TYPES.IActionDispatcher);
    actionDispatcher.value = currentActionDispatcher;
    currentActionDispatcher.request(RequestModelAction.create()).then((response) => {
        currentActionDispatcher.dispatch(response);
    });
});

onBeforeUnmount(() => {
    disposables.value.forEach((disposable) => {
        try {
            disposable.dispose();
        } catch (e) {}
    });
});
</script>
<style scoped>
.hidden {
    display: none;
}
.editor-element {
    width: 100%;
    height: 100%;
}
</style>
<style>
.splitpanes {
    height: 100%;
}

.splitpanes__splitter {
    z-index: 5;
    background: transparent;
    transition: background-color 0s 0s;
}

.splitpanes--vertical .splitpanes__splitter {
    margin-left: -2px;
    margin-right: -2px;
    width: 4px;
}

.splitpanes--horizontal .splitpanes__splitter {
    margin-top: -2px;
    margin-bottom: -2px;
    height: 4px;
}

.splitpanes.splitpanes--dragging .splitpanes__splitter,
.splitpanes__splitter:hover {
    transition: background-color 0s 0.25s;
    background: #007fd4;
}

.splitpanes__pane {
    position: relative;
}

.splitpanes__pane:not(:first-of-type)::before {
    content: "";
    display: block;
    background-color: var(--vp-c-gutter);
    position: absolute;
}

.splitpanes--vertical .splitpanes__pane:not(:first-of-type)::before {
    height: 100%;
    width: 1px;
}

.splitpanes--horizontal .splitpanes__pane:not(:first-of-type)::before {
    height: 1px;
    width: 100%;
}
</style>

// website/src/components/HylimoEditor/index.tsx
import "reflect-metadata";
import { Allotment } from "allotment";
import React, { useContext, useEffect, useRef, useState } from "react";
import { useColorMode } from "@docusaurus/theme-common";
import "allotment/dist/style.css";
import { customDarkTheme, customLightTheme, languageConfiguration, monarchTokenProvider } from "./language";
import {
    MonacoLanguageClient,
    CloseAction,
    ErrorAction,
    MonacoServices,
    MessageTransports
} from "monaco-languageclient";
import {
    BrowserMessageReader,
    BrowserMessageWriter,
    createProtocolConnection
} from "vscode-languageserver-protocol/browser.js";
import { StandaloneServices } from "vscode/services";
import MonacoEditor from "react-monaco-editor";
import { useLocalStorage } from "@rehooks/local-storage";
import { createContainer } from "@hylimo/diagram-ui";
import { ActionHandlerRegistry, IActionDispatcher, TYPES } from "sprotty";
import { RequestModelAction, ActionMessage } from "sprotty-protocol";
import {
    ConfigNotification,
    DiagramActionNotification,
    DiagramOpenNotification,
    RemoteNotification,
    RemoteRequest,
    SetLanguageServerIdNotification
} from "@hylimo/diagram-protocol";
import { DiagramServerProxy, ResetCanvasBoundsAction } from "@hylimo/diagram-ui";
import useResizeObserver from "@react-hook/resize-observer";
import { DynamicLanuageServerConfig } from "@hylimo/diagram-protocol";
import { GlobalStateContext } from "../../theme/Root";
import { Root } from "@hylimo/diagram-common";
import { PublishDocumentRevealNotification } from "@hylimo/diagram-protocol/src";

/**
 * Name of the language
 */
const language = "syncscript";

/**
 * The uri of the TextDocument
 */
const uri = "inmemory://model/1";

/**
 * Editor Component
 *
 * @returns the created editor component
 */
export default function HylimoEditor(): JSX.Element {
    const { setDiagram, setDiagramCode } = useContext(GlobalStateContext);
    const { colorMode } = useColorMode();
    const [code, setCode] = useLocalStorage<string>("code");
    const sprottyWrapper = useRef(null);
    const monaco = useRef<MonacoEditor | null>(null);
    const [actionDispatcher, setActionDispatcher] = useState<IActionDispatcher | undefined>();
    const [languageClient, setLanguageClient] = useState<MonacoLanguageClient | undefined>();
    const [languageServerConfig, setLanguageServerConfig] = useState<DynamicLanuageServerConfig>({
        diagramConfig: {
            theme: colorMode
        }
    });

    useEffect(() => {
        setDiagramCode(code);
        StandaloneServices.initialize({});
        MonacoServices.install();
        const [worker, secondaryWorker] = [0, 1].map(() => new Worker(new URL("./languageServer.ts", import.meta.url)));
        const secondaryConnection = createProtocolConnection(
            new BrowserMessageReader(secondaryWorker),
            new BrowserMessageWriter(secondaryWorker)
        );
        secondaryConnection.listen();
        const reader = new BrowserMessageReader(worker);
        const writer = new BrowserMessageWriter(worker);
        const languageClient = createLanguageClient({ reader, writer });
        languageClient.onNotification(PublishDocumentRevealNotification.type, (message) => {
            const editor = monaco.current?.editor;
            if (editor) {
                const range = message.range;
                const editorRange = {
                    startLineNumber: range.start.line + 1,
                    startColumn: range.start.character + 1,
                    endLineNumber: range.end.line + 1,
                    endColumn: range.end.character + 1
                };
                editor.setSelection(editorRange);
                editor.revealRange(editorRange);
            }
        });
        setLanguageClient(languageClient);
        languageClient.start().then(() => {
            languageClient.sendNotification(DiagramOpenNotification.type, {
                clientId: uri,
                diagramUri: uri
            });

            class LspDiagramServerProxy extends DiagramServerProxy {
                override clientId = uri;

                override initialize(registry: ActionHandlerRegistry): void {
                    super.initialize(registry);
                    languageClient.onNotification(DiagramActionNotification.type, (message) => {
                        if ("newRoot" in message.action && message.action.newRoot != undefined) {
                            setDiagram(message.action.newRoot as Root);
                        }
                        this.messageReceived(message);
                    });
                    languageClient.onNotification(RemoteNotification.type, (message) => {
                        secondaryConnection.sendNotification(RemoteNotification.type, message);
                    });
                    secondaryConnection.onNotification(RemoteNotification.type, (message) => {
                        languageClient.sendNotification(RemoteNotification.type, message);
                    });
                    languageClient.onRequest(RemoteRequest.type, async (request) => {
                        return secondaryConnection.sendRequest(RemoteRequest.type, request);
                    });
                    secondaryConnection.onRequest(RemoteRequest.type, (request) => {
                        return languageClient.sendRequest(RemoteRequest.type, request);
                    });
                    secondaryConnection.sendNotification(SetLanguageServerIdNotification.type, 1);
                }

                protected override sendMessage(message: ActionMessage): void {
                    languageClient.sendNotification(DiagramActionNotification.type, message);
                }
            }

            const container = createContainer("sprotty-container");
            container.bind(LspDiagramServerProxy).toSelf().inSingletonScope();
            container.bind(TYPES.ModelSource).toService(LspDiagramServerProxy);
            const actionDispatcher = container.get<IActionDispatcher>(TYPES.IActionDispatcher);
            actionDispatcher.request(RequestModelAction.create()).then((response) => {
                actionDispatcher.dispatch(response);
            });
            setActionDispatcher(actionDispatcher);
        });
    }, []);

    useResizeObserver(sprottyWrapper, () => {
        const action: ResetCanvasBoundsAction = {
            kind: ResetCanvasBoundsAction.KIND
        };
        actionDispatcher?.dispatch(action);
    });

    useEffect(() => {
        setLanguageServerConfig((currentConfig) => {
            return {
                ...currentConfig,
                diagramConfig: {
                    ...currentConfig.diagramConfig,
                    theme: colorMode
                }
            };
        });
    }, [colorMode]);

    useEffect(() => {
        languageClient?.sendNotification(ConfigNotification.type, languageServerConfig);
    }, [languageServerConfig]);

    useEffect(() => () => setDiagram(null), []);

    return (
        <Allotment>
            <Allotment.Pane>
                <MonacoEditor
                    options={{
                        automaticLayout: true,
                        fixedOverflowWidgets: true,
                        hover: {
                            above: false
                        },
                        suggest: {
                            snippetsPreventQuickSuggestions: false
                        }
                    }}
                    theme={colorMode === "dark" ? "custom-dark" : "custom-light"}
                    editorWillMount={(editor) => {
                        editor.languages.register({ id: language });
                        editor.languages.setLanguageConfiguration(language, languageConfiguration as any);
                        editor.languages.setMonarchTokensProvider(language, monarchTokenProvider as any);
                        editor.editor.defineTheme("custom-dark", customDarkTheme as any);
                        editor.editor.defineTheme("custom-light", customLightTheme as any);
                    }}
                    ref={monaco}
                    language={language}
                    value={code}
                    onChange={(code) => {
                        setCode(code);
                        setDiagramCode(code);
                    }}
                ></MonacoEditor>
            </Allotment.Pane>
            <Allotment.Pane>
                <div ref={sprottyWrapper} className="sprotty-wrapper">
                    <div id="sprotty-container"></div>
                </div>
            </Allotment.Pane>
        </Allotment>
    );
}

/**
 * Creates the language client
 *
 * @param transports used for the JSON rpc
 * @returns the crated MonacoLangaugeClient
 */
function createLanguageClient(transports: MessageTransports): MonacoLanguageClient {
    return new MonacoLanguageClient({
        name: "SyncScript Language Client",
        clientOptions: {
            documentSelector: [{ language }],
            errorHandler: {
                error: () => ({ action: ErrorAction.Continue }),
                closed: () => ({ action: CloseAction.DoNotRestart })
            }
        },
        connectionProvider: {
            get: () => {
                return Promise.resolve(transports);
            }
        }
    });
}
